### ISSUE TITLE
silk-torch-script.py, nvrtc error

### ISSUE THREAD

**Issue by BADAL244** [facebookresearch/silk#39]
/home/badalkumar/facebook/silk/silk/backbones/superpoint/utils.py:36: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if channels == 1:
Traceback (most recent call last):
  File "silk-torch-script.py", line 73, in <module>
    main()
  File "silk-torch-script.py", line 66, in main
    test_on_image_pair(model, script_model, downsampled_images)
  File "silk-torch-script.py", line 20, in test_on_image_pair
    positions_1, descriptors_1, _ = script_model(images)
  File "/home/badalkumar/miniconda3/envs/silk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_div_mul_batch_norm_sigmoid(float* tinput26_1, float* tinput31_1, float* tdenom_1, float* aten_sigmoid, float* aten_mul, float* const_v_, float* const_v__2, float* const_v__1, float* const_v_0, float* const_v_1) {
{
  float v = __ldg(const_v_1 + 0ll);
  float v_1 = __ldg(tinput31_1 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  float v_2 = __ldg(tdenom_1 + ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) % 251424ll + 251424ll * (((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)) / 32182272ll));
  aten_mul[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v * (v_1 / v_2);
if (blockIdx.x<983ll ? 1 : 0) {
if ((long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)<502848ll ? 1 : 0) {
if (blockIdx.x<983ll ? 1 : 0) {
        float const_v__1_1 = __ldg(const_v_ + 0ll);
        float const_v_0_1 = __ldg(const_v_0 + 0ll);
        float v_3 = __ldg(tinput26_1 + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
        float v_4 = __ldg(const_v__1 + 0ll);
        float v_5 = __ldg(const_v__2 + 0ll);
        aten_sigmoid[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = 1.f / (1.f + (expf(0.f - (v_3 * ((rsqrtf(const_v__1_1 + 9.999999747378752e-06f)) * const_v_0_1) + (v_4 - v_5 * ((rsqrtf(const_v__1_1 + 9.999999747378752e-06f)) * const_v_0_1))))));
      }    }  }}
}

**Comment by gleize** [comment]
Hi @BADAL244,

This could be caused by nvidia drivers that are too old (c.f. [here](https://forums.developer.nvidia.com/t/isaac-gym-training-ant-nvrtc-error-invalid-value-for-gpu-architecture-arch/234497)). Try updating your drivers and see if that solves your issue.

**Comment by gleize** [comment]
No activity. Closing now.
