### ISSUE TITLE
Could you please provide a docker

### ISSUE THREAD

**Issue by Adolfhill** [facebookresearch/silk#59]
Thanks for your impressive work!
It is a trouble to set environment. Could you please provide a docker for training and evaluating?

**Comment by gleize** [comment]
Hi @Adolfhill,

We do not have plan for making a docker as of now, but it might change if there is popular demand for it (I'll leave that issue opened to gather that feedback).

Regarding setting the environment, we've tested the reproducibility a few times and did not have any issues with it. What troubles are you having ? Maybe I can help.

**Comment by Adolfhill** [comment]
Thank you for your help. I have solved the issue. 
The issue occurred while installing jax. I think it might be because, for some reason, Chinese developers are unable to access https://storage.googleapis.com/jax-releases/jax_cuda_releases.html.

**Comment by Adolfhill** [comment]
hello, We I try to run ./bin/public-pull-assets as you mentioned in doc/usage/setup.md, there is an error:
======================================================================
ERROR: test_keep_mutual_correspondences_only (losses.info_nce.loss_test._UnitTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data0/silk/lib/losses/info_nce/loss_test.py", line 96, in test_keep_mutual_correspondences_only
    corr_0, corr_1 = corr[:, 0], corr[:, 1]
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3816, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 3843, in _gather
    y = lax.gather(
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/lax/slicing.py", line 284, in gather
    return gather_p.bind(
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/dispatch.py", line 115, in apply_primitive
    return compiled_fun(*args)
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/dispatch.py", line 200, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/home/adolf/miniconda3/envs/silk/lib/python3.8/site-packages/jax/_src/dispatch.py", line 895, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Could not find the corresponding function

----------------------------------------------------------------------
Ran 18 tests in 3.892s

FAILED (errors=1)

It seems that maybe it is caused by the error of the version of jax or jaxlib?
I use the jaxlib-0.3.25+cuda11.cudnn82-cp38-cp38-manylinux2014_x86_64.whl downloaded from  https://storage.googleapis.com/jax-releases/jax_cuda_releases.html and jax==0.3.25.

**Comment by Satama1** [comment]
> Thank you for your help. I have solved the issue. The issue occurred while installing jax. I think it might be because, for some reason, Chinese developers are unable to access https://storage.googleapis.com/jax-releases/jax_cuda_releases.html.

你好,请问你是怎么解决的,我也是在下载cuda这一步超时,使用VPN也没有用.
